from mongoengine import *
import config
connect(config.db_name)

class BidDayOffer(Document):
	SETTLEMENTDATE = DateTimeField()
	DUID = StringField()
	BIDTYPE = StringField()
	BIDSETTLEMENTDATE = DateTimeField()
	OFFERDATE = DateTimeField()
	VERSIONNO = IntField()
	PARTICIPANTID = StringField()
	DAILYENERGYCONSTRAINT = FloatField()
	REBIDEXPLANATION = StringField()
	PRICEBAND1 = FloatField()
	PRICEBAND2 = FloatField()
	PRICEBAND3 = FloatField()
	PRICEBAND4 = FloatField()
	PRICEBAND5 = FloatField()
	PRICEBAND6 = FloatField()
	PRICEBAND7 = FloatField()
	PRICEBAND8 = FloatField()
	PRICEBAND9 = FloatField()
	PRICEBAND10 = FloatField()
	MINIMUMLOAD = FloatField()
	T1 = FloatField()
	T2 = FloatField()
	T3 = FloatField()
	T4 = FloatField()
	NORMALSTATUS = StringField()
	LASTCHANGED = DateTimeField()
	MR_FACTOR = FloatField()
	ENTRYTYPE = StringField()
	rowhash = StringField(unique=True)

class BidPerOffer(Document):
	
	SETTLEMENTDATE = DateTimeField()
	DUID = StringField()
	BIDTYPE = StringField()
	BIDSETTLEMENTDATE = DateTimeField()
	OFFERDATE = DateTimeField()
	PERIODID = StringField()
	VERSIONNO = IntField()
	MAXAVAIL = FloatField()
	FIXEDLOAD = FloatField()
	ROCUP = FloatField()
	ROCDOWN = FloatField()
	ENABLEMENTMIN = FloatField()
	ENABLEMENTMAX = FloatField()
	LOWBREAKPOINT = FloatField()
	HIGHBREAKPOINT = FloatField()
	BANDAVAIL1 = FloatField()
	BANDAVAIL2 = FloatField()
	BANDAVAIL3 = FloatField()
	BANDAVAIL4 = FloatField()
	BANDAVAIL5 = FloatField()
	BANDAVAIL6 = FloatField()
	BANDAVAIL7 = FloatField()
	BANDAVAIL8 = FloatField()
	BANDAVAIL9 = FloatField()
	BANDAVAIL10 = FloatField()
	LASTCHANGED = DateTimeField()
	PASAAVAILABILITY = FloatField()
	INTERVAL_DATETIME = DateTimeField()
	MR_CAPACITY = FloatField()
	rowhash = StringField(unique=True)

